apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_e31efcc97fb8
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_URL
              value: "mongodb://username:password@mongo:27017/dbname"
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
